#!/usr/bin/env python3
"""Build `glorpui_hints` from the game's own files, worded as Glorp UI words it.

    python3 mods/glorpui_hints/tools/generate.py           write the mod
    python3 mods/glorpui_hints/tools/generate.py --check   write nothing, say what would change

What the societal value tooltip lists, per direction:

* **Off** (the usual): under the game's own «To further push» title, what the
  country can take or already has working for it today; under the game's own
  «Not yet available» title, what it could get later. Both lists come from the
  game's `common/`: privileges, reforms and policies (`core.py`), and every other
  source that pushes a value (`gates.py`, `languages.py`).
  Each «not yet» row opens with its age, «(IV)», a link to what it takes.
* **On** — Glorp UI's «show unavailable suggestions» switch, or this mod's own in
  the CMF menu, either one: the same two lists, then what this country can never
  take (linked the same way: whose it is shows in its conditions), then every
  other source unfiltered.

**With Glorp UI and without it.** Every name the mod defines is its own
(`svx_*`), so nothing collides with Glorp UI's and nothing needs it at runtime.
Glorp UI's part is the wording: the privilege, reform and policy lines are built
from Glorp UI's own hint files in all eleven languages, read here at build time,
and its switch is honoured. The template this mod overrides is the one Glorp UI
overrides too, so with both installed this mod has to load after Glorp UI.
"""

from __future__ import annotations

import argparse
import collections
import re
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
MOD = TOOLS.parent
REPO = MOD.parent.parent
sys.path.insert(0, str(TOOLS))
sys.path.insert(0, str(REPO / "tools"))

import core  # noqa: E402
import gates as svx_gates  # noqa: E402
import languages as svx_languages  # noqa: E402
import pdx  # noqa: E402
import refs  # noqa: E402
import scan_sources  # noqa: E402

GAME = REPO / "reference/game"
HEADER = ("# Auto-generated by mods/glorpui_hints/tools/generate.py from the EU5 game "
          "files. Do not edit by hand.")

GUI = "in_game/gui/svx_extra_societal_value_hints.gui"
# Under main_menu/, where the game's own and Calidad de Vida's working concept
# live; 1.2.3 put them under in_game/ and the line lost everything from the
# object's name on (run 10-04, 06:1x).
CONCEPTS = "main_menu/common/game_concepts/svx_requirements.txt"
SCRIPTED_GUIS = "in_game/common/scripted_guis/svx_requirements.txt"
CUSTOM = "in_game/common/customizable_localization/svx_hint_loc.txt"
VALUES = "in_game/common/script_values/svx_hint_script_values.txt"
TRIGGERS = "in_game/common/scripted_triggers/svx_hint_triggers.txt"
SUPPRESS = "in_game/common/scripted_effects/svx_hint_scopes.txt"

# Written by earlier designs and gone from this one. Removed on every build so a
# file left behind cannot keep printing: the Russian
# `glorpui_generated_societal_value_hints_l_russian.yml` in particular has Glorp
# UI's own name and would replace Glorp UI's own Russian.
OBSOLETE = [
    "in_game/gui/custom_cooltip.gui",
    "in_game/common/game_concepts/svx_requirements.txt",
    "in_game/common/customizable_localization/svx_extra_hint_loc.txt",
    "in_game/common/customizable_localization/svx_unlock_gate.txt",
    "in_game/common/script_values/svx_extra_hint_script_values.txt",
] + ["main_menu/localization/%s/%s_l_%s.yml" % (lang, name, lang)
     for lang in svx_languages.LANGUAGES
     for name in ("glorpui_generated_societal_value_hints", "svx_extra_hints")]

# The scopes the `.gui` hands the script values. Glorp UI's are `glorpui_sv`
# and `glorpui_country`; these are the mod's own.
SV_SCOPE, COUNTRY_SCOPE = "svx_sv", "svx_country"

# Where the objects of the other sources live, for their gates.
SOURCE_DIRS = {
    "building_types": "in_game/common/building_types",
    "missions": "in_game/common/missions",
    "parliament_types": "in_game/common/parliament_types",
    "cabinet_actions": "in_game/common/cabinet_actions",
    "religious_aspects": "in_game/common/religious_aspects",
    "religious_schools": "in_game/common/religious_schools",
    "estates": "in_game/common/estates",
    "subject_types": "in_game/common/subject_types",
    "chivalric_orders": "in_game/common/chivalric_orders",
    "parliament_issues": "in_game/common/parliament_issues",
    "advances": "in_game/common/advances",
    "bureaucracies": "in_game/common/bureaucracies",
}
CORE_SOURCES = {"estate_privileges", "government_reforms", "laws"}
# Only one of these is in force at a time, so a weaker one is pointless while a
# stronger one already is.
EXCLUSIVE_SOURCES = {"employment_systems"}
# Pushes that scale with how much is spent on them: the number is a ceiling.
MAINTAINED_SOURCES = {"bureaucracies"}
CABINET_SUFFIX = "_progress_cabinet_efficiency"
AUTO_MODIFIERS = "in_game/common/auto_modifiers"

# Glorp UI's line for each of the three kinds, as their hint files write it.
GLORP_HINTS = "main_menu/localization/{lang}/glorpui_generated_societal_value_hints_l_{lang}.yml"
GLORP_CODES = {"PV": "privilege", "R": "reform", "P": "policy"}
LINE_CODE = {"privilege": "pv", "reform": "r", "policy": "p", "io_policy": "io",
             "catalog": "c", "scaled": "sc", "conditional": "cd", "cabinet": "cab",
             "estate_power": "ep"}


def fail(message: str) -> None:
    raise SystemExit("generate.py: " + message)


def number(value: float) -> str:
    text = ("%.3f" % value).rstrip("0")
    if len(text.split(".")[1]) < 2:
        text = "%.2f" % value
    return "+" + text


def glorp_lines(glorp: Path) -> dict[str, dict[str, str]]:
    """language -> kind -> Glorp UI's line, with `{key}` and `{value}` holes.

    Every line of one kind in one language must reduce to the same shape;
    anything else means Glorp UI changed how it writes them, and the build stops
    rather than wording a line some other way.
    """
    out: dict[str, dict[str, str]] = {}
    line = re.compile(r'^ GLORP_UI_SVH_[A-Z_]+?_(PV|R|P)_[A-Z0-9_]+: *"(.*)"\s*$', re.M)
    for lang in svx_languages.LANGUAGES:
        path = glorp / GLORP_HINTS.format(lang=lang)
        if not path.is_file():
            fail("%s missing — is Glorp UI in reference/mods?" % path)
        shapes: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
        for match in line.finditer(path.read_text(encoding="utf-8-sig")):
            text = re.sub(r"(\[Show\w+Name)\('\w+'\)", r"\1('{key}')", match.group(2))
            text = re.sub(r"[+]\d+\.\d+", "{value}", text, count=1)
            shapes[GLORP_CODES[match.group(1)]][text] += 1
        out[lang] = {}
        for kind in GLORP_CODES.values():
            found = shapes.get(kind)
            if not found or len(found) != 1:
                fail("%s: %s lines come in %d shapes, expected one: %s"
                     % (path.name, kind, len(found or {}), list(found or {})[:3]))
            out[lang][kind] = next(iter(found))
    return out


def auto_modifier_gates() -> dict[str, str]:
    """auto modifier -> its `potential_trigger`, as one line.

    «Высокое самообладание правителя» printed for an Orthodox Bulgaria on
    2026-09-28: `positive_self_control` is only in force where
    `modifier:allow_self_control` is, and the line had no gate at all.
    """
    found = {}
    for name, (block, _) in pdx.objects(GAME / AUTO_MODIFIERS).items():
        line = core.own_trigger(pdx.get(block, "potential_trigger"))
        if line:
            found[name] = line
    return found


ADVANCES = core.Advances(GAME)


def other_lines(findings: list[dict]) -> list[dict]:
    """Every push outside privileges, reforms and policies that the mod lists."""
    caches = {source: svx_gates.scan_objects(str(GAME), rel) for source, rel in SOURCE_DIRS.items()}
    status_owners = svx_gates.status_owners(str(GAME))
    auto_gates = auto_modifier_gates()
    known = core.steps(GAME)
    scaled = set(svx_languages.SCALED_KEYS) | set(svx_languages.NEW_SCALED_KEYS)
    conditional = set(svx_languages.CONDITIONAL_KEYS) | set(svx_languages.NEW_CONDITIONAL_KEYS)

    lines = []
    for row in findings:
        source, obj, axis = row["source_type"], row["object"], row["axis"]
        value = core.amount(row["raw_value"], known)
        if value is None or value <= 0 or source in CORE_SOURCES:
            continue
        base = {"direction": axis, "object": obj, "value": value, "up_to": False,
                "source_type": source, "soon": None}
        if source == "estates":
            # `high_power`: in force only above the power threshold, and scaled
            # past it, so the number is a ceiling (his note, 2026-09-28).
            base.update(kind="estate_power", up_to=True,
                        now=["country_has_estate = estate_type:%s" % obj])
        elif source in svx_languages.CATALOG_REGISTRIES:
            gate = svx_gates.gate_for(source, obj, caches.get(source, {}),
                                      {"status_owners": status_owners,
                                       "block": row["path"][1] if len(row["path"]) > 1 else ""})
            now, reach = list(gate["now"]), list(gate["reach"])
            if source in EXCLUSIVE_SOURCES:
                peers = sorted({other["object"] for other in findings
                                if other["source_type"] == source and other["axis"] == axis
                                and other["object"] != obj
                                and (core.amount(other["raw_value"], known) or 0) >= value})
                now += ["NOT = { has_employment_system = employment_system:%s }" % p
                        for p in peers + [obj]]
            base.update(kind="catalog", now=now, up_to=source in MAINTAINED_SOURCES)
            if source == "advances" and obj in ADVANCES.age:
                base["why"] = {"age": ADVANCES.age[obj]}
            # «Not yet» needs a real reach to be about: without one, failing
            # «now» means displaced or done, not pending.
            if reach and reach != now:
                base["soon"] = reach + ["NOT = { AND = { %s } }" % " ".join(now)]
        elif obj in scaled or obj in conditional:
            base.update(kind="scaled" if obj in scaled else "conditional",
                        up_to=obj in scaled,
                        now=[auto_gates[obj]] if obj in auto_gates else [])
        elif obj.endswith(CABINET_SUFFIX):
            base.update(kind="cabinet", now=[])
        else:
            continue
        lines.append(base)
    return lines


def collect() -> dict[str, list[dict]]:
    """direction -> its lines, takeable kinds first, each kind strongest first."""
    lines = core.collect(GAME) + other_lines(scan_sources.scan(str(GAME)))
    order = {"privilege": 0, "reform": 1, "policy": 2, "io_policy": 3, "estate_power": 4,
             "catalog": 5, "scaled": 6, "conditional": 7, "cabinet": 8}
    out: dict[str, list[dict]] = collections.defaultdict(list)
    seen = set()
    for line in sorted(lines, key=lambda l: (order[l["kind"]], -l["value"], l["object"])):
        identity = (line["direction"], line["kind"], line.get("source_type"), line["object"])
        if identity in seen:
            continue
        seen.add(identity)
        code = LINE_CODE[line["kind"]]
        line["name"] = "svx_%s_%s_%s" % (line["direction"], code, line["object"])
        out[line["direction"]].append(line)
    return out


def line_text(line: dict, lang: str, glorp: dict[str, dict[str, str]]) -> str:
    phrases = svx_languages.PHRASES[lang]
    value = (phrases["up_to"] if line["up_to"] else "") + number(line["value"])
    kind = line["kind"]
    if kind in ("privilege", "reform", "policy"):
        return glorp[lang][kind].replace("{key}", line["object"]).replace("{value}", value)
    if kind == "io_policy":
        label = phrases["io_policy"].format(ref="[ShowPolicyName('%s')]" % line["object"])
        return "@hint! %s: #color_green %s#!\\n" % (label, value)
    if kind == "estate_power":
        # «Власть священников выше порога: до +0.33» — the game's own name for
        # the estate's power, through a data function, inside words of our own.
        label = phrases["estate_power"].format(
            ref="[ShowModifierTypeName('global_%s_power')]" % line["object"])
        return "@hint! %s: #color_green %s#!\\n" % (label, value)
    if kind == "catalog":
        source = line["source_type"]
        reference = "#TOOLTIP:%s,%s #L $%s$#!#!" % (
            svx_languages.CATALOG_REGISTRIES[source], line["object"], line["object"])
        concept = svx_languages.CATALOG_CONCEPTS.get(source)
        if concept is None:
            label = "%s %s" % (phrases["build_in_capital"], reference)
        else:
            label = phrases["catalog"].format(concept=concept, ref=reference)
        return "@hint! %s: #color_green %s#!\\n" % (label, value)
    if kind == "scaled":
        return "@hint! %s #help (%s)#!: #color_green %s#!\\n" % (
            phrases["scaled"][line["object"]], phrases["scales"], value)
    if kind == "conditional":
        return "@hint! %s: #color_green %s#!\\n" % (phrases["conditional"][line["object"]], value)
    if kind == "cabinet":
        return "@hint! %s #help (%s)#!\\n" % (phrases["cabinet"], phrases["cabinet_scales"])
    raise AssertionError(kind)


def axis_pairs() -> list[tuple[str, str, str]]:
    pairs = []
    for name, _ in pdx.objects(GAME / "in_game/common/societal_values").items():
        match = re.match(r"^([a-z_]+?)_vs_([a-z_]+)$", name)
        if match:
            pairs.append((match.group(1), match.group(2), name))
    return pairs


def custom_entry(name: str, key: str, trigger: list[str]) -> list[str]:
    return custom_choice(name, [(key, trigger)])


def custom_choice(name: str, choices: list[tuple[str, list[str]]]) -> list[str]:
    """The first key whose trigger holds, or nothing."""
    out = ["%s = {" % name, "\ttype = country"]
    for key, trigger in choices:
        out += ["\ttext = {", "\t\ttrigger = {"] + ["\t\t\t%s" % t for t in trigger] + [
            "\t\t}", "\t\tlocalization_key = %s" % key, "\t}"]
    return out + ["\ttext = {", "\t\tlocalization_key = empty_text", "\t}", "}", ""]


ROMAN = ["", "I", "II", "III", "IV", "V", "VI", "VII", "VIII"]


def soon_reasons(line: dict) -> list[tuple[str, list[str]]]:
    """Why a «not yet» line is not yet, in the order it is asked (his ask
    10-04: the game names the age, ours named nothing): the advance that unlocks
    it while the country lacks it, the age it belongs to while that is still to
    come, else the game's own «requirements not yet met»."""
    why = line.get("why") or {}
    out = []
    if why.get("advance"):
        out.append(("_ADV", ["NOT = { %s }" % why["advance_have"]]))
    if why.get("age"):
        out.append(("_AGE", ["NOT = { current_age_or_later = { age = %s } }" % why["age"]]))
    return out + [("_REQ", [])]


def requirements_name(line: dict) -> str | None:
    """The scripted GUI and the tooltip widget that list this line's gates."""
    if not line.get("needs") or line["kind"] not in NAME_OF:
        return None
    return "svx_req_%s_%s" % (line["kind"], line["object"])


def before_number(text: str, note: str) -> str:
    at = text.rfind(": #color_green")
    if at < 0:
        at = text.rfind("\\n")
    return text[:at] + note + text[at:]


def age_label(line: dict) -> str | None:
    """The age an object belongs to, as the numeral his ask wants: its own age,
    else the age of the earliest advance that unlocks it."""
    why = line.get("why") or {}
    age = why.get("age") or why.get("advance_age")
    return "(%s)" % ROMAN[core.age_number(age)] if age else None


def linked(text: str, line: dict) -> str:
    """The row opened by its age, «(IV)» (or «(!)» without one), a link to what
    it takes to get the object (his ask 10-04). `[key|E]`, the concept's name
    being the bracket, as Calidad de Vida's working mod concept is used; at the
    row's start, because a row too long for its width is drawn smaller while
    the link's hover area is not (the run before: at the row's end it hovered
    on «(» or nowhere)."""
    at = text.find("@hint!")
    # After the hint icon and the no-break space Glorp UI puts after it.
    at = at + len("@hint!") + 1 if at >= 0 else 0
    return text[:at] + "[%s|E] " % requirements_name(line) + text[at:]


def soon_text(text: str, line: dict, reason: str) -> str:
    """A «not yet» row: linked when the object has conditions; else its age,
    «(IV)», before its number while the advance or the age is still to come."""
    if requirements_name(line):
        return linked(text, line)
    why = line.get("why") or {}
    if reason == "_ADV":
        return before_number(text, " #help (%s)#!" % ROMAN[core.age_number(why["advance_age"])])
    if reason == "_AGE":
        return before_number(text, " #help (%s)#!" % ROMAN[core.age_number(why["age"])])
    return text


# Whether the country has the object already: such a row is in none of the
# three lists.
HAS = {"privilege": "has_estate_privilege = estate_privilege:%s",
       "reform": "has_reform = government_reform:%s",
       "policy": "has_policy = %s"}


def never_gate(line: dict) -> list[str]:
    """A row for the «not available to this country» list (his ask 10-04: what
    belongs to Lithuania, what to the Ottomans): neither now nor later, and not
    already in force."""
    gate = ["NOT = { %s }" % HAS[line["kind"]] % line["object"]]
    if line["now"]:
        gate.append("NOT = { AND = { %s } }" % " ".join(line["now"]))
    if line["soon"]:
        gate.append("NOT = { AND = { %s } }" % " ".join(line["soon"]))
    return gate


def requirements(by_direction: dict[str, list[dict]]) -> dict[str, dict]:
    """scripted GUI name -> the triggers it checks and the bracket it shows,
    once per object with conditions."""
    out: dict[str, dict] = {}
    for lines in by_direction.values():
        for line in lines:
            name = requirements_name(line)
            if name:
                out[name] = {"needs": line["needs"], "label": age_label(line) or "(!)"}
    return dict(sorted(out.items()))


_LOC: dict[str, dict[str, str]] = {}


def _game_loc(key: str) -> str | None:
    """The game's text for a key when both languages in the tree have it as
    plain text, else None (rus_nakaz_decision.title is English-only)."""
    for lang in ("english", "russian"):
        if lang not in _LOC:
            _LOC[lang] = {}
            for path in (GAME / "main_menu/localization" / lang).rglob("*.yml"):
                for m in re.finditer(r'^ +([^:#\s]+):\d* +"(.*)"', path.read_text("utf-8-sig", "replace"), re.M):
                    _LOC[lang].setdefault(m.group(1), m.group(2))
    texts = [_LOC[lang].get(key) for lang in ("english", "russian")]
    if any(t is None or "[" in t or "$" in t for t in texts):
        return None
    return texts[0]


def _tag(code: str) -> str | None:
    tag = code.upper()
    return tag if re.fullmatch(r"[A-Z]{3}", tag) and _game_loc(tag) else None


def flag_sources(flags: set[str]) -> dict[str, dict]:
    """flag -> how to word a gate that is only `has_variable = flag`.

    The game words it «НЕ имеет переменной: masaniellos_fight_flag», which says
    nothing about whose it is (his run 10-04). What sets the variable does: a
    decision (its title, its `tags`), a country's event (its title when that is
    plain text, the country from flavor_<tag>.txt), a disaster's event (the
    disaster's name), or a rebel demand (rebel_demand_flavor_<tag>_N). A flag set
    anywhere else keeps the game's wording."""
    sets = collections.defaultdict(list)
    for path in sorted((GAME / "in_game").rglob("*.txt")):
        text = path.read_text("utf-8-sig", "replace")
        if "set_variable" not in text:
            continue
        tops = [(m.start(), m.group(1)) for m in re.finditer(r"^([A-Za-z0-9_.]+)\s*=\s*\{", text, re.M)]
        for m in re.finditer(r"set_variable\s*=\s*(?:\{[^}]*?name\s*=\s*)?([A-Za-z0-9_]+)", text):
            if m.group(1) not in flags:
                continue
            top = next((name for at, name in reversed(tops) if at < m.start()), None)
            body = text[[at for at, name in tops if name == top][0]:m.start()] if top else ""
            sets[m.group(1)].append((path.relative_to(GAME / "in_game"), top, body))
    out = {}
    for flag, hits in sets.items():
        found = None
        for rel, top, body in hits:
            folder, stem = rel.parts[-2], rel.stem
            if folder == "decisions" and top:
                name = _game_loc(top + ".title")
                listed = re.search(r"\btags\s*=\s*\{([^}]*)\}", body)
                tags = [t for t in (listed.group(1).split() if listed else []) if _tag(t)]
                if not tags:
                    tags = [t for t in re.findall(r"has_or_had_tag\s*=\s*([A-Z]{3})\b", body) if _tag(t)]
                if not tags and _tag(top.split("_")[0]):
                    tags = [top.split("_")[0].upper()]
                if name and tags:
                    found = {"kind": "decision", "name": top + ".title", "tags": tags}
                elif tags:
                    found = {"kind": "decision_country", "name": None, "tags": tags}
            elif folder == "disaster" and _game_loc(stem):
                found = {"kind": "disaster", "name": stem, "tags": []}
            elif folder in ("DHE", "events") and stem.lower().startswith("flavor_") and _tag(stem[7:]):
                name = _game_loc("%s.title" % top) if top else None
                tags = [stem[7:].upper()]
                found = ({"kind": "event", "name": top + ".title", "tags": tags} if name else {"kind": "event_country", "name": None, "tags": tags})
            elif folder == "rebel_demands" and top:
                m = re.match(r"rebel_demand_flavor_([a-z]{3})_", top)
                if m and _tag(m.group(1)):
                    found = {"kind": "rebels", "name": None, "tags": [m.group(1).upper()]}
            if found:
                break
        if found:
            out[flag] = found
    return out


def flag_word(source: dict, lang: str) -> str:
    words = svx_languages.FLAG_WORDS[lang][source["kind"]]
    return words.format(name="$%s$" % source["name"] if source["name"] else "",
                        tags=", ".join("$%s$" % t for t in source["tags"]))


# `X ?= { ... }` scope changes: suspected first for «Крейты» (1.2.8), cleared
# by the probe, kept since every country has these scopes and `=` reads plainer.
SAFE_SCOPES = re.compile(r"\b(culture|religion|capital) \?= \{")
SAFE_VALUES = re.compile(r"\b(group|region|area|sub_continent|language_family) \?= ")


# IsValidTooltip draws a failing OR as «Всё из перечисленного:» with nothing
# under it (his 1.2.9 probe, 10-04: the same triggers outside an OR printed).
# calc_true_if is the same test with its own block and words.
OR_BLOCK = re.compile(r"\bOR = \{")
NOR_BLOCK = re.compile(r"\bNOR = \{")


def worded(need: str, sources: dict[str, dict]) -> str:
    """One `is_valid` line, with what the game words badly worded by us."""
    need = SAFE_SCOPES.sub(r"\1 = {", need)
    need = SAFE_VALUES.sub(r"\1 = ", need)
    need = OR_BLOCK.sub("calc_true_if = { amount >= 1", need)
    need = NOR_BLOCK.sub("calc_true_if = { amount = 0", need)

    def flag(m: re.Match) -> str:
        # a variable the game already wraps in its own custom_tooltip stays
        if m.group(1) not in sources or re.search(r"custom_tooltip = \{ text = \S+\s*$", need[:m.start()]):
            return m.group(0)
        return "custom_tooltip = { text = svx_flag_%s %s }" % (m.group(1), m.group(0))
    return re.sub(r"has_variable = ([A-Za-z0-9_]+)", flag, need)


def scripted_guis(reqs: dict[str, dict], sources: dict[str, dict]) -> str:
    out = [HEADER, "# One per object a «not yet» line names: its `is_valid` is every gate the",
           "# game puts on that object, and IsValidTooltip has the game word them.", ""]
    for name, req in reqs.items():
        out += ["%s = {" % name, "\tscope = country", "\tis_valid = {"]
        out += ["\t\t%s" % worded(n, sources) for n in req["needs"]]
        out += ["\t}", "}", ""]
    return "\n".join(out)


# The game's own concepts' icons (main_menu/common/game_concepts/00_game_concepts.txt).
TEXTURE_OF = {"privilege": "flat_icons/privilege", "reform": "flat_icons/reforms",
              "policy": "alerts_icons/setup_a_law"}
NAME_OF = {"privilege": "ShowEstatePrivilegeName", "reform": "ShowGovernmentReformName",
           "policy": "ShowPolicyName"}


def concepts(reqs: dict[str, dict]) -> str:
    """One game concept per object: the link the age bracket is. A mod concept
    with no texture renders as nothing (docs/pitfalls/localization.md); each
    carries the icon of the game's own concept for its kind."""
    out = [HEADER, "# The «(IV)» on a «not yet» line links here; the concept's text is the",
           "# game's own wording of the object's conditions (svx_requirements.txt).", ""]
    for name in reqs:
        kind = name[len("svx_req_"):].split("_", 1)[0]
        out += ["%s = {" % name, '\ttexture = "%s"' % TEXTURE_OF[kind], "\tshown_in_encyclopedia = no", "}", ""]
    return "\n".join(out)


def concept_words(reqs: dict[str, dict], lang: str, sources: dict[str, dict]) -> str:
    out = [HEADER, "l_%s:" % lang]
    for flag, source in sorted(sources.items()):
        out.append(' svx_flag_%s: "%s"' % (flag, flag_word(source, lang)))
    for name, req in reqs.items():
        kind, key = name[len("svx_req_"):].split("_", 1)
        out.append(' game_concept_%s: "%s"' % (name, req["label"]))
        out.append(' game_concept_%s_desc: "[%s(\'%s\')]\\n$LIST_TITLE_REQUIREMENTS$\\n'
                   '[GetScriptedGui(\'%s\').IsValidTooltip(GuiScope.SetRoot(GetPlayer.MakeScope).End)]"'
                   % (name, NAME_OF[kind], key, name))
    return "\n".join(out) + "\n"


def build() -> dict[str, str]:
    """published path -> text, for every file the mod is made of."""
    glorp = glorp_lines(refs.mod("glorp.ui.rio"))
    by_direction = collect()
    pairs = axis_pairs()
    directions = [d for pair in pairs for d in pair[:2]]
    missing = sorted(set(by_direction) - set(directions))
    if missing:
        fail("pushes towards directions no axis has: %s" % missing)
    files: dict[str, str] = {}

    # --- the gates: words in none of them, one file for every language -------
    custom = [HEADER, "# One entry per line that has a gate: the line prints only while",
              "# its trigger holds. «now» is what the country can take today, «soon»",
              "# what it could get later (game 1.4's own «not yet available»).", ""]
    for direction in directions:
        for line in by_direction.get(direction, []):
            key = line["name"].upper()
            if line["now"]:
                custom += custom_entry(line["name"] + "_now", key, line["now"])
            if line["soon"]:
                custom += custom_choice(line["name"] + "_soon", [
                    (key + "_SOON" + reason, line["soon"] + extra)
                    for reason, extra in soon_reasons(line)])
            if requirements_name(line):
                custom += custom_entry(line["name"] + "_never", key + "_NEVER", never_gate(line))
    files[CUSTOM] = "\n".join(custom)

    # --- whether each list has anything to show --------------------------------
    values = [HEADER, "# The .gui sets scope:%s (the societal value) and scope:%s"
              % (SV_SCOPE, COUNTRY_SCOPE), "# (the player); each value is 1 when its list has a line to show.", ""]

    def visible(name: str, pair: str, gates: list[list[str]] | None) -> list[str]:
        out = ["%s = {" % name, "\tvalue = 0"]
        if gates is not None and not gates:
            return out + ["}", ""]
        out += ["\tif = {", "\t\tlimit = {",
                "\t\t\tscope:%s = societal_value_type:%s" % (SV_SCOPE, pair),
                "\t\t\tscope:%s = {" % COUNTRY_SCOPE,
                "\t\t\t\thas_societal_value = societal_value_type:%s" % pair]
        if gates:
            out.append("\t\t\t\tOR = {")
            out += ["\t\t\t\t\tAND = { %s }" % " ".join(g) for g in gates]
            out.append("\t\t\t\t}")
        out += ["\t\t\t}", "\t\t}", "\t\tadd = 1", "\t}", "}", ""]
        return out

    for left, right, pair in pairs:
        values += visible("svx_axis_%s" % pair, pair, None)
        for direction in (left, right):
            lines = by_direction.get(direction, [])
            # A line with no gate always prints, so the list always shows.
            now_gates = None if any(not l["now"] for l in lines) else [l["now"] for l in lines]
            values += visible("svx_now_visible_%s" % direction, pair, now_gates)
            values += visible("svx_soon_visible_%s" % direction, pair,
                              [l["soon"] for l in lines if l["soon"]])
            values += visible("svx_never_visible_%s" % direction, pair,
                              [never_gate(l) for l in lines if requirements_name(l)])
    files[VALUES] = "\n".join(values)

    # --- the three takeability triggers, Glorp UI's own bodies -----------------
    files[TRIGGERS] = "\n".join([
        HEADER,
        "# Whether a reform, policy or privilege can be taken now. Glorp UI's",
        "# bodies under this mod's names; PREV inside each block is the country.",
        "",
        "svx_reform_core = {",
        "\tgovernment_reform:$KEY$ = {",
        "\t\tis_implementable_in = PREV",
        "\t\tNOT = { is_fully_implemented_in = PREV }",
        "\t}",
        "}",
        "",
        "# is_fully_implemented_in on a policy is true whenever its law is in force,",
        "# so the current policy is ruled out with has_policy instead.",
        "svx_policy_core = {",
        "\tpolicy:$KEY$ = {",
        "\t\tis_implementable_in = PREV",
        "\t}",
        "\tNOT = { has_policy = $KEY$ }",
        "\tlaw:$LAW$ = {",
        "\t\tOR = {",
        "\t\t\tis_fully_implemented_in = PREV",
        "\t\t\tis_implementable_in = PREV",
        "\t\t}",
        "\t}",
        "}",
        "",
        "svx_privilege_takeable = {",
        "\testate_privilege:$KEY$ = {",
        "\t\tis_implementable_in = PREV",
        "\t\tNOT = { is_fully_implemented_in = PREV }",
        "\t}",
        "}",
        ""])
    files[SUPPRESS] = "\n".join([
        HEADER,
        "# The .gui sets these two scopes; this only tells the script checker",
        "# they exist. It never runs.",
        "svx_hint_scopes = {",
        "\tif = {",
        "\t\tlimit = { always = no }",
        "\t\tsave_scope_as = %s" % SV_SCOPE,
        "\t\tsave_scope_as = %s" % COUNTRY_SCOPE,
        "\t}",
        "}",
        ""])

    # --- the words, once per language ------------------------------------------
    for lang in svx_languages.LANGUAGES:
        phrases = svx_languages.PHRASES[lang]
        out = [HEADER, "l_%s:" % lang]
        for key, text in phrases["titles"].items():
            out.append(' %s: "%s"' % (key, text))
        for direction in directions:
            lines = by_direction.get(direction, [])
            now_body, soon_body, never_body, all_body = [], [], [], []
            for line in lines:
                key = line["name"].upper()
                text = line_text(line, lang, glorp)
                if line["now"] or line["soon"]:
                    out.append(' %s: "%s"' % (key, text))
                if line["soon"]:
                    for reason, _ in soon_reasons(line):
                        out.append(' %s_SOON%s: "%s"' % (key, reason, soon_text(text, line, reason)))

                now_body.append("[Player.Custom('%s_now')]" % line["name"] if line["now"] else text)
                if line["soon"]:
                    soon_body.append("[Player.Custom('%s_soon')]" % line["name"])

                if requirements_name(line):
                    out.append(' %s_NEVER: "%s"' % (key, linked(text, line)))
                    never_body.append("[Player.Custom('%s_never')]" % line["name"])
                if line["kind"] not in NAME_OF:
                    # With the switch on, the game's own lists stand in for the
                    # three takeable kinds; everything else is listed whole.
                    # (1.2.4 listed those too, unfiltered: «каша», 10-04.)
                    all_body.append(text)
            upper = direction.upper()
            out.append(' SVX_NOW_%s: "%s"' % (upper, "".join(now_body)))
            out.append(' SVX_SOON_%s: "%s"' % (upper, "".join(soon_body)))
            out.append(' SVX_NEVER_%s: "%s"' % (upper, "".join(never_body)))
            out.append(' SVX_ALL_%s: "%s"' % (upper, "".join(all_body)))
        files["main_menu/localization/%s/svx_hints_l_%s.yml" % (lang, lang)] = "\n".join(out) + "\n"

        menu = [HEADER, "# CMM derives every key below from the mod id and the setting id,",
                "# and a key it cannot find shows as the raw key on screen.", "l_%s:" % lang]
        # A setting only English and Russian word yet shows in English rather
        # than as its raw key.
        words = dict(svx_languages.PHRASES["english"]["menu"], **phrases["menu"])
        menu += [' %s: "%s"' % (k, v.replace('"', '\\"')) for k, v in words.items()]
        files["main_menu/localization/%s/svx_menu_l_%s.yml" % (lang, lang)] = "\n".join(menu) + "\n"

    for lang, fixes in svx_languages.GLORP_UI_FIXES.items():
        out = [HEADER, "# Glorp UI's own interface keys, repaired where its text is broken.",
               "# Only the languages whose text is actually broken get a file.", "l_%s:" % lang]
        out += [' %s: "%s"' % (k, v) for k, v in fixes.items()]
        files["main_menu/localization/%s/svx_glorpui_fixes_l_%s.yml" % (lang, lang)] = "\n".join(out) + "\n"

    files[GUI] = gui(pairs, by_direction)
    reqs = requirements(by_direction)
    sources = flag_sources({f for req in reqs.values() for n in req["needs"]
                            for f in re.findall(r"has_variable = ([A-Za-z0-9_]+)", n)})
    files[SCRIPTED_GUIS] = scripted_guis(reqs, sources)
    files[CONCEPTS] = concepts(reqs)
    for lang in svx_languages.LANGUAGES:
        files["main_menu/localization/%s/svx_requirements_l_%s.yml" % (lang, lang)] = concept_words(reqs, lang, sources)
    return files


def gui(pairs, by_direction) -> str:
    # On while either switch is: Glorp UI's own (a variable on the player's
    # country, which simply reads unset without Glorp UI) or this mod's in the
    # CMF menu. `CMMSettingIsRegistered` keeps the menu's answer «off» until
    # registration has run.
    show_game = ("Or(Player.MakeScope.GetVariable('showUnavailableSocietalValueSuggestions').IsSet,"
                 " And(CMMSettingIsRegistered('svx__show_all'),"
                 "CMMValueEqualsOne(CMMSettingValue('svx__show_all'))))")

    def scope_value(name: str) -> str:
        return ("GreaterThan_CFixedPoint(GuiScope.AddScope('%s', SocietalValue.MakeScope)"
                ".AddScope('%s', Player.MakeScope).ScriptValue('%s'), '(CFixedPoint)0')"
                % (SV_SCOPE, COUNTRY_SCOPE, name))

    def block(visible: str, title: str, textcontext: str, height: int = 160) -> list[str]:
        return ["\t\tTooltipScrolledStringPairList = {",
                "\t\t\tvisible = \"[%s]\"" % visible,
                "\t\t\tblockoverride \"block_scrollarea\" {",
                "\t\t\t\tmaximumsize = { -1 %d }" % height,
                "\t\t\t}",
                "",
                "\t\t\tblockoverride \"block_title\" {",
                "\t\t\t\ttext = \"%s\"" % title,
                "\t\t\t\tdefault_format = \"#help\"",
                "\t\t\t}",
                "",
                "\t\t\ttextcontext = \"%s\"" % textcontext,
                "\t\t}",
                ""]

    out = [HEADER,
           "# Overrides the game's SocietalValueCountryLeft/Right_tooltip, which Glorp UI",
           "# overrides as well: with both installed this mod loads after Glorp UI.",
           "# Every name below is this mod's own or the game's.",
           ""]
    for side, index in (("Left", 0), ("Right", 1)):
        out += ["template SocietalValueCountry%s_tooltip {" % side,
                "\tusing = SocietalValue%s_tooltip" % side,
                "\tblockoverride \"societal_value_%s_tooltip_extra\" {" % side.lower(),
                "",
                "\t\t# This mod's lists under the game's own two titles; with either switch",
                "\t\t# on, also what this country can never take and every other source",
                "\t\t# (10-04: the game's own lists there named neither age nor owner).",
                ""]
        for pair in pairs:
            direction = pair[index]
            upper = direction.upper()
            out += block(scope_value("svx_now_visible_%s" % direction),
                         "TO_MOVE_FURTHER_TO_%s" % side.upper(), "[Localize('SVX_NOW_%s')]" % upper)
            out += block(scope_value("svx_soon_visible_%s" % direction),
                         "SV_HINT_NOT_YET_AVAILABLE", "[Localize('SVX_SOON_%s')]" % upper)
            out += block("And(%s, %s)" % (show_game, scope_value("svx_never_visible_%s" % direction)),
                         "SVX_NEVER", "[Localize('SVX_NEVER_%s')]" % upper)
        for pair in pairs:
            direction = pair[index]
            if not any(l["kind"] not in NAME_OF for l in by_direction.get(direction, [])):
                continue
            out += block("And(%s, %s)" % (show_game, scope_value("svx_axis_%s" % pair[2])),
                         "SVX_EVERYTHING", "[Localize('SVX_ALL_%s')]" % direction.upper())
        out += ["\t}", "}", ""]
    return "\n".join(out)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="write nothing")
    args = parser.parse_args(argv)

    files = build()
    changed = []
    for rel, text in sorted(files.items()):
        path = MOD / rel
        old = path.read_text(encoding="utf-8-sig") if path.is_file() else None
        if old != text:
            changed.append(rel)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8-sig", newline="\n")
    gone = [rel for rel in OBSOLETE if (MOD / rel).is_file()]
    if not args.check:
        for rel in gone:
            (MOD / rel).unlink()

    counts = collections.Counter()
    for lines in collect().values():
        for line in lines:
            counts[line["kind"]] += 1
    print("lines: " + ", ".join("%s %d" % kv for kv in sorted(counts.items())))
    verb = "would change" if args.check else "changed"
    print("%d file(s) %s, %d obsolete file(s) %s" % (
        len(changed), verb, len(gone), "to remove" if args.check else "removed"))
    for rel in changed + gone:
        print("  " + rel)
    return 1 if args.check and (changed or gone) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
