#!/usr/bin/env python3
"""The societal values window, with a second bar for where the value is heading.

Vanilla draws one bar per side of a societal value: how far the country stands
from the middle, `SocietalValueItem.GetPosition`. It never draws the other
number it has - `SocietalValueItem.GetDirection`, which the arrow in the middle
of the row prints as text. Glorp UI added a thin second bar for it under the
first, and that is the one thing of theirs the owner wants kept after the mod
itself leaves the playset.

**This is vanilla's own template with three hunks applied**, not a copy of Glorp
UI's file and not a window written here: the file is read out of
`reference/game`, the two progress bars are replaced by a `vbox` of three, and
the middle badge moves two pixels. Everything else in the window is whatever the
game ships, so a patch that changes the window arrives here on the next
`tools/refresh.py` instead of being silently overwritten by a year-old copy.

Nothing in it is Glorp UI's: `progressbar_bar_small`, `progress_bar_goldish`
and `progress_bar_blue_alt` are the game's own bar skins, used by the game's own
`map_markers.gui` and `production_lateralview.gui`, and `GetDirection` is a
vanilla data function. The mod needs no other mod to draw this.

**A template is not a window.** It costs nothing while the panel is closed -
there is no entry in `gui/scripted_widgets/`, no always-live widget and no
`GetScriptedGui`. It is redefined by load order, which is how Glorp UI's own
copy worked, and the game's `societal_values_lateralview.gui` keeps its
`lateralview`, its `select_menu_left` and its `types Values` untouched.

Usage:
    python3 mods/glorpui_hints/tools/generate_values_window.py [--check]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
MOD = TOOLS.parent
sys.path.insert(0, str(MOD.parent.parent / "tools"))

import refs  # noqa: E402

SOURCE = refs.GAME_GUI / "societal_values_lateralview.gui"
TEMPLATE = "societal_values"
OUT = MOD / "in_game/gui/svx_societal_values_window.gui"

HEADER = """\
# Auto-generated by mods/glorpui_hints/tools/generate_values_window.py from the EU5 game
# files. Do not edit by hand.
#
# The game's own `template societal_values`, with a second bar per side for
# `SocietalValueItem.GetDirection` - where the value is heading, which vanilla
# only prints as a number on the arrow between the two halves. The three hunks
# below are marked `# svx:`; everything else is the game's file, carried
# verbatim so a patch to the window is not lost behind this one.
#
# Redefines the template by load order. The rest of
# in_game/gui/societal_values_lateralview.gui - the lateralview, the select
# menu and `types Values` - stays the game's.
"""

# Each hunk is vanilla's text and what replaces it. Both are matched exactly and
# must occur exactly once: a window the game has changed under us fails the run
# rather than producing a file that half applies.
HUNKS = [
    # The left bar. `GetPosition` keeps the bar it always had; the gold one
    # under it is `GetDirection` on the same scale, drawn only while the value
    # is drifting leftwards. The third is the same bar at zero, so that the row
    # keeps its height while the value drifts the other way - without it the
    # two sides of the window stand at different heights.
    ("""\t\t\t\t\t\t# LEFT PRGORESSBAR
\t\t\t\t\t\tprogressbar = {
\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\tsize = { 0 6 }
\t\t\t\t\t\t\tusing = progressbar_bar_small
\t\t\t\t\t\t\tusing = progress_bar_blue_alt_left
\t\t\t\t\t\t\tvalue = "[Abs_float(Min_float(SocietalValueItem.GetPosition, '(float)0'))]"
\t\t\t\t\t\t\tinvertprogress = yes
\t\t\t\t\t\t}
""",
     """\t\t\t\t\t\t# LEFT PRGORESSBAR
\t\t\t\t\t\tvbox = { # svx: the position bar, and under it where it is heading
\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding

\t\t\t\t\t\t\tprogressbar = {
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tsize = { 0 6 }
\t\t\t\t\t\t\t\tusing = progressbar_bar_small
\t\t\t\t\t\t\t\tusing = progress_bar_blue_alt_left
\t\t\t\t\t\t\t\tvalue = "[Abs_float(Min_float(SocietalValueItem.GetPosition, '(float)0'))]"
\t\t\t\t\t\t\t\tinvertprogress = yes
\t\t\t\t\t\t\t}

\t\t\t\t\t\t\tprogressbar = { # svx: drifting left
\t\t\t\t\t\t\t\tvisible = "[LessThan_float(SocietalValueItem.GetDirection, '(float)0')]"
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tsize = { 0 4 }
\t\t\t\t\t\t\t\tusing = progressbar_bar_small
\t\t\t\t\t\t\t\tusing = progress_bar_goldish
\t\t\t\t\t\t\t\tvalue = "[Abs_float(Multiply_float(SocietalValueItem.GetDirection, '(float)100.0'))]"
\t\t\t\t\t\t\t\tinvertprogress = yes
\t\t\t\t\t\t\t}

\t\t\t\t\t\t\tprogressbar = { # svx: drifting the other way - empty, to hold the height
\t\t\t\t\t\t\t\tvisible = "[Not(LessThan_float(SocietalValueItem.GetDirection, '(float)0'))]"
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tsize = { 0 4 }
\t\t\t\t\t\t\t\tusing = progressbar_bar_small
\t\t\t\t\t\t\t\tusing = progress_bar_goldish
\t\t\t\t\t\t\t\tvalue = "[Abs_float('(float)0')]"
\t\t\t\t\t\t\t\tinvertprogress = yes
\t\t\t\t\t\t\t}
\t\t\t\t\t\t}
"""),
    # The right bar, the same three, mirrored.
    ("""\t\t\t\t\t\t# RIGHT PRGORESSBAR
\t\t\t\t\t\tprogressbar = {
\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\tsize = { 0 6 }
\t\t\t\t\t\t\tusing = progressbar_bar_small
\t\t\t\t\t\t\tusing = progress_bar_blue_alt
\t\t\t\t\t\t\tvalue = "[Abs_float(Max_float(SocietalValueItem.GetPosition, '(float)0'))]"
\t\t\t\t\t\t}
""",
     """\t\t\t\t\t\t# RIGHT PRGORESSBAR
\t\t\t\t\t\tvbox = { # svx: the position bar, and under it where it is heading
\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding

\t\t\t\t\t\t\tprogressbar = {
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tsize = { 0 6 }
\t\t\t\t\t\t\t\tusing = progressbar_bar_small
\t\t\t\t\t\t\t\tusing = progress_bar_blue_alt
\t\t\t\t\t\t\t\tvalue = "[Abs_float(Max_float(SocietalValueItem.GetPosition, '(float)0'))]"
\t\t\t\t\t\t\t}

\t\t\t\t\t\t\tprogressbar = { # svx: drifting right
\t\t\t\t\t\t\t\tvisible = "[GreaterThan_float(SocietalValueItem.GetDirection, '(float)0')]"
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tsize = { 0 4 }
\t\t\t\t\t\t\t\tusing = progressbar_bar_small
\t\t\t\t\t\t\t\tusing = progress_bar_goldish
\t\t\t\t\t\t\t\tvalue = "[Abs_float(Multiply_float(SocietalValueItem.GetDirection, '(float)100.0'))]"
\t\t\t\t\t\t\t}

\t\t\t\t\t\t\tprogressbar = { # svx: drifting the other way - empty, to hold the height
\t\t\t\t\t\t\t\tvisible = "[Not(GreaterThan_float(SocietalValueItem.GetDirection, '(float)0'))]"
\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\tsize = { 0 4 }
\t\t\t\t\t\t\t\tusing = progressbar_bar_small
\t\t\t\t\t\t\t\tusing = progress_bar_goldish
\t\t\t\t\t\t\t\tvalue = "[Abs_float('(float)0')]"
\t\t\t\t\t\t\t}
\t\t\t\t\t\t}
"""),
    # The badge with the arrow and the number sits over the bars; four more
    # pixels of bar push it down, so it moves two back up. Glorp UI made the
    # same two moves for the same reason and this is what the owner is used to
    # seeing.
    ("""\t\t\t\t\tposition = {0 -7 }
""",
     """\t\t\t\t\tposition = { 0 -5 } # svx: -7, moved for the second bar
"""),
    # The number on the badge, one point larger. Not layout - the badge sits on
    # a busier row now and Glorp UI's reading of it is what the owner has been
    # looking at for months.
    ("""\t\t\t\t\t\t\tfontsize = 12
""",
     """\t\t\t\t\t\t\tfontsize = 13 # svx: 12
"""),
]


def template_text(text: str, name: str) -> str:
    """`template <name> { ... }`, braces matched, comments and strings skipped."""
    start = re.search(r"^template %s \{" % re.escape(name), text, re.M)
    if not start:
        raise SystemExit("%s: no template %s" % (SOURCE, name))
    depth = 0
    index = start.end() - 1
    while index < len(text):
        char = text[index]
        if char == '"':
            index = text.find('"', index + 1)
            if index < 0:
                break
        elif char == "#":
            index = text.find("\n", index)
            if index < 0:
                break
            continue
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start.start():index + 1]
        index += 1
    raise SystemExit("%s: template %s does not close" % (SOURCE, name))


def build() -> str:
    body = template_text(SOURCE.read_text(encoding="utf-8-sig"), TEMPLATE)
    for old, new in HUNKS:
        count = body.count(old)
        if count != 1:
            raise SystemExit(
                "%s: the game's window has changed - this hunk is in it %d times,"
                " not once. Re-read it against the file before rebuilding:\n%s"
                % (SOURCE.relative_to(refs.REPO), count, old))
        body = body.replace(old, new)
    return HEADER + "\n" + body.rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="report, write nothing")
    args = parser.parse_args(argv[1:])

    text = build()
    was = OUT.read_text(encoding="utf-8-sig") if OUT.is_file() else None
    if args.check:
        print("%s: %s" % (OUT.relative_to(refs.REPO),
                          "up to date" if was == text else "out of date"))
        return 0 if was == text else 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8-sig", newline="\n")
    print("%s: %d lines, %d of them the game's own"
          % (OUT.relative_to(refs.REPO), text.count("\n"),
             text.count("\n") - sum(new.count("\n") for _, new in HUNKS)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
